const UserActionTypes = {
  GET_USERS_ASYNC: 'GET_USERS_ASYNC',
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  GET_USERS_FAILURE: 'GET_USERS_FAILURE',
  SET_SELECTED_USER: 'SET_SELECTED_USER'
};

export default UserActionTypes;
